# ==================
# Project Details
# ==================
name: "jaffle_shop"
config-version: 2
require-dbt-version:
- ">=1.5.0"
version: "3.0.0"
profile: "default"

# ==================
# File Path Configs
# ==================
test-paths:
- "data-tests"
clean-targets:
- "target"
- "dbt_packages"
snapshot-paths:
- "snapshots"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analyses"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  dbt_date:time_zone: "America/Los_Angeles"

# ==================
# Model Configs
# ==================
models:
  jaffle_shop:
    marts:
      "+materialized": "table"
    staging:
      "+materialized": "view"

# ==================
# Seed Configs
# ==================
seeds:
  jaffle_shop:
    "+schema": "raw"
