name: jaffle_shop
description: ''
version: 0.0.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/sftp_to_snowflake_airflow_job:
    name: sftp_to_snowflake_airflow_job
    description: ''
    fabricUID: 2
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-05-07 12:06:50'
    author: ashish@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-07 12:01:23'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/stg_orders.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/order_items:
    name: order_items
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/order_items.sql
    - .prophecy/ide/models/order_items.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/supplies:
    name: supplies
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/supplies.sql
    - .prophecy/ide/models/supplies.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/orders.sql
    - .prophecy/ide/models/orders.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/customers.sql
    - .prophecy/ide/models/customers.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/products:
    name: products
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/products.sql
    - .prophecy/ide/models/products.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/stg_order_items:
    name: stg_order_items
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/staging/stg_order_items.sql
    - .prophecy/ide/models/stg_order_items.json
    - models/staging/stg_order_items.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/stg_customers.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/locations:
    name: locations
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/locations.sql
    - .prophecy/ide/models/locations.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/metricflow_time_spine:
    name: metricflow_time_spine
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/marts/metricflow_time_spine.sql
    - .prophecy/ide/models/metricflow_time_spine.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/stg_locations:
    name: stg_locations
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/staging/stg_locations.sql
    - .prophecy/ide/models/stg_locations.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/stg_products:
    name: stg_products
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/staging/stg_products.sql
    - .prophecy/ide/models/stg_products.json
    - models/staging/stg_products.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmodels/stg_supplies:
    name: stg_supplies
    schema: null
    description: null
    author: ashish@prophecy.io
    files:
    - models/staging/stg_supplies.sql
    - .prophecy/ide/models/stg_supplies.json
    - models/staging/stg_supplies.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-07 12:01:25'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/postgres__cents_to_dollars:
    name: postgres__cents_to_dollars
    macroType: expression
    description: null
    author: ashish@prophecy.io
    files:
    - macros/cents_to_dollars.sql
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmacros/cents_to_dollars:
    name: cents_to_dollars
    macroType: query
    description: null
    author: ashish@prophecy.io
    files:
    - macros/cents_to_dollars.sql
    - .prophecy/ide/macros/cents_to_dollars.json
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: ashish@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmacros/default__cents_to_dollars:
    name: default__cents_to_dollars
    macroType: expression
    description: null
    author: ashish@prophecy.io
    files:
    - macros/cents_to_dollars.sql
    createdAt: '2024-05-07 12:01:25'
  .prophecy/metadata/sqlmacros/bigquery__cents_to_dollars:
    name: bigquery__cents_to_dollars
    macroType: expression
    description: null
    author: ashish@prophecy.io
    files:
    - macros/cents_to_dollars.sql
    createdAt: '2024-05-07 12:01:25'
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/ecom:
    name: ecom
    description: E-commerce data for the Jaffle Shop
    author: ashish@prophecy.io
    files:
    - models/staging/__sources.yml
    createdAt: '2024-05-07 12:01:25'
    tables:
    - name: raw_customers
      schema: null
      description: One record per person who has purchased one or more items
      author: ashish@prophecy.io
      createdAt: '2024-05-07 12:01:25'
    - name: raw_orders
      schema: null
      description: One record per order (consisting of one or more order items)
      author: ashish@prophecy.io
      createdAt: '2024-05-07 12:01:25'
    - name: raw_items
      schema: null
      description: Items included in an order
      author: ashish@prophecy.io
      createdAt: '2024-05-07 12:01:25'
    - name: raw_stores
      schema: null
      description: null
      author: ashish@prophecy.io
      createdAt: '2024-05-07 12:01:25'
    - name: raw_products
      schema: null
      description: One record per SKU for items sold in stores
      author: ashish@prophecy.io
      createdAt: '2024-05-07 12:01:25'
    - name: raw_supplies
      schema: null
      description: One record per supply per SKU of items sold in stores
      author: ashish@prophecy.io
      createdAt: '2024-05-07 12:01:25'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: ashish@prophecy.io
  createdAt: '2024-05-07 12:01:23'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
